spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5000
    socket-timeout: 10000

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: blog-serve
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: sk-ba2596c1b95e4c6e8f27cb3d735dcafe
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7

server:
  tomcat:
    connection-timeout: 60000
    max-keep-alive-requests: 100
    keep-alive-timeout: 60000
  servlet:
    async:
      timeout: 60000
    session:
      timeout: 30m

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzt.blog.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-enums-package: com.zzt.blog.enums
  global-config:
    db-config:
      id-type: auto
xf:
  config:
    hostUrl: "https://spark-api.xf-yun.com/v2.1/chat"
    appId: "aec4eb2c"
    apiSecret: "NmZmOTNhMGE3MmQxNzVjOGU3NjkzMWQ5"
    apiKey: "6891529a0faa25aaa456c6313fa2cd76"
    # 最大响应时间，单位：秒
    maxResponseTime: 30